### ISSUE TITLE
Received invalid percentage: 

### ISSUE THREAD

**Issue by poudenes** [Scriptman/ESPHome_ITHO_Eco_Fan_CC1101#17]
Hi All,

I see this error in HA log
```
2023-04-30 08:19:02.542 ERROR (MainThread) [homeassistant.components.template.fan] Received invalid percentage:  for entity fan.mechanical_ventilation
```
I checked everything and seems ok. (copy paste without any changes)
```
fan:
  - platform: template
    fans:
      mechanical_ventilation:
        friendly_name: "Mechanische afzuiging"
        value_template: >
          {{ "off" if states('sensor.fan_speed') == 'Standby' else "on" }}
        percentage_template: >
          {% set speedperc = {'standby': 0, 'low': 33, 'medium': 66, 'high': 100} %}
          {{speedperc [states('sensor.fan_speed')]}}
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.fan_high
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.fan_standby
        set_percentage:
          service: switch.turn_on
          data_template:
            entity_id: >
              {% set id_mapp = {0: 'switch.fan_standby', 33:'switch.fan_low', 66:'switch.fan_medium', 100:'switch.fan_high'} %}
              {{id_mapp[percentage]}}
        speed_count: 2
```
Medium is not showing:
<img width="319" alt="Scherm­afbeelding 2023-04-30 om 08 30 53" src="https://user-images.githubusercontent.com/4399532/235339227-f37257d9-7b5c-41ce-856e-793ea50f3d04.png">

**Comment by christiaandm** [comment]
If you change `speed_count: 2` to `speed_count: 3` medium will show up.

**Comment by poudenes** [comment]
I have that already and still have the message

```
- platform: template
  fans:
    mechanical_ventilation:
      friendly_name: "Mechanische afzuiging"

      value_template: >
        {{ "off" if states('sensor.fan_speed') == 'off' else "on" }}

      percentage_template: >
        {% set speed = {'off': 0, 'low': 33, 'medium': 66, 'high': 100} %}
        {{speed [states('sensor.fan_speed')]}}

      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.fan_high
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.fan_standby
      set_percentage:
        service: switch.turn_on
        data_template:
          entity_id: >
            {% set id_mapp = {0: 'switch.fan_standby', 33:'switch.fan_low', 66:'switch.fan_medium', 100:'switch.fan_high'} %}
            {{id_mapp[percentage]}}
      speed_count: 3
```
